package com.first_love.constant

//Keys
const val EXTRA_DATA = "EXTRA_DATA"
const val EXTRA_LIST = "EXTRA_LIST"
const val EXTRA_FLAG = "EXTRA_FLAG"

const val EXTRA_MOBILE_NUMBER = "EXTRA_MOBILE_NUMBER"
const val EXTRA_COUNTRY_CODE = "EXTRA_COUNTRY_CODE"
const val EXTRA_ACCESS_TOKEN = "EXTRA_ACCESS_TOKEN"
const val EXTRA_USERNAME = "EXTRA_NAME"
const val EXTRA_DOB = "EXTRA_DOB"
const val EXTRA_GENDER = "EXTRA_GENDER"
const val EXTRA_INTERESTED = "EXTRA_INTERESTED"
const val EXTRA_UNIVERSITY = "EXTRA_UNIVERSITY"
